/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.MarkTableDao;
import dao.StudentDao;
import dao.SubjectDao;
import java.awt.CardLayout;
import java.sql.Date;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.MarkTable;
import model.Student;
import model.Subject;

/**
 *
 * @author Admin
 */
public class GiaoDien1 extends javax.swing.JFrame {
    SubjectDao subjectDao;
    StudentDao studentDao;
    MarkTableDao markTableDao;
    DefaultTableModel dTM3;
    DefaultTableModel dTM2;
    DefaultTableModel dTM4;
    /**
     * Creates new form NewJFrame
     */
    CardLayout cardLayout;
    public GiaoDien1() {
        initComponents();
        this.setLocationRelativeTo(null);
        subjectDao=new SubjectDao();
        studentDao=new StudentDao();
        markTableDao=new MarkTableDao();
        dTM3=new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };
        //dTM3=new DefaultTableModel();
        subjectTable.setModel(dTM3);
        dTM3.addColumn("Mã môn");
        dTM3.addColumn("Tên môn");
        dTM3.addColumn("Số tín");
        setTableData3(subjectDao.getALLSubject());
        cardLayout=(CardLayout) parentPanel.getLayout();
        subjectTable.getColumnModel().getColumn(0).setPreferredWidth(50);
        subjectTable.getColumnModel().getColumn(1).setPreferredWidth(400);
        subjectTable.getColumnModel().getColumn(2).setPreferredWidth(50);
        
        dTM2=new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row,int column){
                return false;
            }
        };
        studentTable.setModel(dTM2);
        dTM2.addColumn("Mã sinh viên");
        dTM2.addColumn("Họ vè tên");
        dTM2.addColumn("Giới tính");
        dTM2.addColumn("Ngày sinh");
        dTM2.addColumn("Lớp");
        dTM2.addColumn("Địa chỉ");
        setTableData2(studentDao.getAllStudent());
        studentTable.getColumnModel().getColumn(0).setPreferredWidth(20);
        studentTable.getColumnModel().getColumn(1).setPreferredWidth(180);
        studentTable.getColumnModel().getColumn(2).setPreferredWidth(20);
        studentTable.getColumnModel().getColumn(3).setPreferredWidth(80);
        studentTable.getColumnModel().getColumn(4).setPreferredWidth(20);
        studentTable.getColumnModel().getColumn(5).setPreferredWidth(180);
        
        dTM4=new DefaultTableModel(){
            @Override
            public boolean isCellEditable(int row, int column) {
               return false;
            }
            
        };
        mTTable.setModel(dTM4);
        dTM4.addColumn("Mã bảng điểm");
        dTM4.addColumn("Tên môn");
        dTM4.addColumn("Lớp môn");
        dTM4.addColumn("Ngày thi");
        dTM4.addColumn("Học kỳ");
        setTableData4(markTableDao.getAllMarkTable());
        mTTable.getColumnModel().getColumn(0).setPreferredWidth(30);
        mTTable.getColumnModel().getColumn(1).setPreferredWidth(150);
        mTTable.getColumnModel().getColumn(2).setPreferredWidth(30);
        mTTable.getColumnModel().getColumn(3).setPreferredWidth(80);
        mTTable.getColumnModel().getColumn(4).setPreferredWidth(150);
    }
    private void setTableData3(List<Subject> subjects){
        for(Subject subject:subjects){
            dTM3.addRow(new Object[]{subject.getMaMon(),subject.getTenMon(),subject.getSoTin()});
        }
    }
    private void setTableData2(List<Student> students){
        for(Student student:students){
            dTM2.addRow(new Object[]{student.getMaSv(),student.getHoTen(),student.getGioiTinh(),
                student.getNgaySinh(),student.getLop(),student.getDiaChi()});
        }
    }
    private void setTableData4(List<MarkTable> markTables){
        for(MarkTable markTable:markTables){
            dTM4.addRow(new Object[]{markTable.getMaBangDiem(),markTableDao.getTenMon(markTable.getMaMon()),
                markTable.getLopMon(),markTable.getNgayThi(),markTable.getHocKi()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel9 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        trangChu = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        sinhVien = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        monHoc = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        bangDiem = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        diem = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        parentPanel = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        p2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentTable = new javax.swing.JTable();
        add2 = new javax.swing.JButton();
        edit2 = new javax.swing.JButton();
        delete2 = new javax.swing.JButton();
        search2 = new javax.swing.JTextField();
        timKiem2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjectTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        maMon3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tenMon3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        soTin3 = new javax.swing.JTextField();
        refresh3 = new javax.swing.JButton();
        add3 = new javax.swing.JButton();
        edit3 = new javax.swing.JButton();
        delete3 = new javax.swing.JButton();
        submit3 = new javax.swing.JButton();
        search3 = new javax.swing.JTextField();
        timKiem3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        p4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        mTTable = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        maBangDiem4 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        maMon4 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        lopMon4 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        ngayThi4 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        hocKy4 = new javax.swing.JComboBox<>();
        refresh4 = new javax.swing.JButton();
        add4 = new javax.swing.JButton();
        edit4 = new javax.swing.JButton();
        delete4 = new javax.swing.JButton();
        submit4 = new javax.swing.JButton();
        seeMark4 = new javax.swing.JButton();
        search4 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        timKiem4 = new javax.swing.JButton();
        p5 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        search5 = new javax.swing.JTextField();
        seeMark = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(0, 0));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("TRƯỜNG ĐẠI HỌC XÂY DỰNG");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 153));
        jLabel11.setText("National University of Civil Engineering");

        trangChu.setBackground(new java.awt.Color(54, 33, 89));
        trangChu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                trangChuMousePressed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Trang chủ");

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_home_25px.png"))); // NOI18N

        javax.swing.GroupLayout trangChuLayout = new javax.swing.GroupLayout(trangChu);
        trangChu.setLayout(trangChuLayout);
        trangChuLayout.setHorizontalGroup(
            trangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(trangChuLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        trangChuLayout.setVerticalGroup(
            trangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, trangChuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(trangChuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(12, 12, 12))
        );

        sinhVien.setBackground(new java.awt.Color(54, 33, 89));
        sinhVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                sinhVienMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sinh viên");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_student_male_25px.png"))); // NOI18N

        javax.swing.GroupLayout sinhVienLayout = new javax.swing.GroupLayout(sinhVien);
        sinhVien.setLayout(sinhVienLayout);
        sinhVienLayout.setHorizontalGroup(
            sinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sinhVienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        sinhVienLayout.setVerticalGroup(
            sinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sinhVienLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sinhVienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(12, 12, 12))
        );

        monHoc.setBackground(new java.awt.Color(54, 33, 89));
        monHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                monHocMousePressed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Môn học");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_book_25px_1.png"))); // NOI18N

        javax.swing.GroupLayout monHocLayout = new javax.swing.GroupLayout(monHoc);
        monHoc.setLayout(monHocLayout);
        monHocLayout.setHorizontalGroup(
            monHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monHocLayout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        monHocLayout.setVerticalGroup(
            monHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, monHocLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(monHocLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addGap(12, 12, 12))
        );

        bangDiem.setBackground(new java.awt.Color(54, 33, 89));
        bangDiem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bangDiemMousePressed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Bảng điểm");

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_test_25px.png"))); // NOI18N

        javax.swing.GroupLayout bangDiemLayout = new javax.swing.GroupLayout(bangDiem);
        bangDiem.setLayout(bangDiemLayout);
        bangDiemLayout.setHorizontalGroup(
            bangDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bangDiemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        bangDiemLayout.setVerticalGroup(
            bangDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bangDiemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bangDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(12, 12, 12))
        );

        diem.setBackground(new java.awt.Color(54, 33, 89));
        diem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                diemMousePressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Điểm sinh viên");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_exam_25px.png"))); // NOI18N

        javax.swing.GroupLayout diemLayout = new javax.swing.GroupLayout(diem);
        diem.setLayout(diemLayout);
        diemLayout.setHorizontalGroup(
            diemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4))
        );
        diemLayout.setVerticalGroup(
            diemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diemLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(diemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(12, 12, 12))
        );

        jPanel1.setBackground(new java.awt.Color(54, 33, 89));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(trangChu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(sinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(monHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(bangDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(diem, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(383, 383, 383)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(trangChu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sinhVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(monHoc, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bangDiem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(diem, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        parentPanel.setLayout(new java.awt.CardLayout());

        p1.setBackground(new java.awt.Color(235, 245, 245));

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/b.png"))); // NOI18N

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(511, Short.MAX_VALUE))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel20)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        parentPanel.add(p1, "card2");

        p2.setBackground(new java.awt.Color(255, 255, 255));

        studentTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        studentTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(studentTable);

        add2.setText("Thêm");
        add2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add2ActionPerformed(evt);
            }
        });

        edit2.setText("Sửa");
        edit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit2ActionPerformed(evt);
            }
        });

        delete2.setText("Xóa");
        delete2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete2ActionPerformed(evt);
            }
        });

        timKiem2.setText("Tìm kiếm");
        timKiem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiem2ActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Tìm kiếm theo mã,tên hoặc theo lớp");

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(add2)
                .addGap(47, 47, 47)
                .addComponent(edit2)
                .addGap(46, 46, 46)
                .addComponent(delete2)
                .addGap(336, 336, 336))
            .addGroup(p2Layout.createSequentialGroup()
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(p2Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(p2Layout.createSequentialGroup()
                                .addComponent(search2, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(timKiem2)))))
                .addContainerGap(200, Short.MAX_VALUE))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timKiem2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add2)
                    .addComponent(edit2)
                    .addComponent(delete2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        parentPanel.add(p2, "card3");

        p3.setBackground(new java.awt.Color(255, 255, 255));

        subjectTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(subjectTable);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Mã môn");

        maMon3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel3.setText("Tên môn");

        tenMon3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel4.setText("Số tín");

        soTin3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        refresh3.setText("Làm mới");
        refresh3.setPreferredSize(new java.awt.Dimension(60, 23));
        refresh3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh3ActionPerformed(evt);
            }
        });

        add3.setText("Thêm");
        add3.setPreferredSize(new java.awt.Dimension(60, 23));
        add3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add3ActionPerformed(evt);
            }
        });

        edit3.setText("Sửa");
        edit3.setPreferredSize(new java.awt.Dimension(60, 23));
        edit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit3ActionPerformed(evt);
            }
        });

        delete3.setText("Xóa");
        delete3.setPreferredSize(new java.awt.Dimension(60, 23));
        delete3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete3ActionPerformed(evt);
            }
        });

        submit3.setText("Xác nhận sửa");
        submit3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(edit3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(refresh3, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(add3, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                    .addComponent(delete3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(maMon3)
                            .addComponent(tenMon3)
                            .addComponent(soTin3, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(submit3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(maMon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tenMon3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(soTin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refresh3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(edit3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(delete3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(submit3)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        timKiem3.setText("Tìm kiếm");
        timKiem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiem3ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Tìm theo tên môn hoặc mã môn");

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(p3Layout.createSequentialGroup()
                                .addComponent(search3, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32)
                                .addComponent(timKiem3)))))
                .addContainerGap(127, Short.MAX_VALUE))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timKiem3))
                .addGap(28, 28, 28)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );

        parentPanel.add(p3, "card4");

        p4.setBackground(new java.awt.Color(255, 255, 255));

        mTTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(mTTable);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel9.setText("Mã bảng điểm");
        jLabel9.setToolTipText("");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        maBangDiem4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel21.setText("Mã môn");
        jLabel21.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        maMon4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel22.setText("Lớp môn");
        jLabel22.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        lopMon4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel23.setText("Ngày thi");
        jLabel23.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        ngayThi4.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(0, 0, 0)));

        jLabel24.setText("Học kỳ");
        jLabel24.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        hocKy4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Năm học 2017-2018-Học kỳ 1", "Năm học 2017-2018-Học kỳ 2", "Năm học 2018-2019-Học kỳ 1", "Năm học 2018-2019-Học kỳ 2", "Năm học 2019-2020-Học kỳ 1", "Năm học 2019-2020-Học kỳ 2", " " }));

        refresh4.setText("Làm mới");
        refresh4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refresh4ActionPerformed(evt);
            }
        });

        add4.setText("Thêm");
        add4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add4ActionPerformed(evt);
            }
        });

        edit4.setText("Sửa");
        edit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit4ActionPerformed(evt);
            }
        });

        delete4.setText("Xóa");
        delete4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delete4ActionPerformed(evt);
            }
        });

        submit4.setText("Xác nhận sửa");
        submit4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submit4ActionPerformed(evt);
            }
        });

        seeMark4.setText("Xem điểm");
        seeMark4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeMark4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE, 66, Short.MAX_VALUE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(maMon4, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                            .addComponent(lopMon4)
                            .addComponent(ngayThi4)
                            .addComponent(hocKy4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(maBangDiem4)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(refresh4)
                            .addComponent(add4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(edit4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(submit4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(delete4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seeMark4))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maBangDiem4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(maMon4, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lopMon4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ngayThi4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hocKy4, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(add4)
                    .addComponent(edit4)
                    .addComponent(delete4))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(refresh4)
                    .addComponent(submit4)
                    .addComponent(seeMark4))
                .addGap(24, 24, 24))
        );

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabel26.setText("Tìm kiếm theo mã bảng điểm, tên môn ,lớp môn ");

        timKiem4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        timKiem4.setText("Tìm kiếm");
        timKiem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                timKiem4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p4Layout = new javax.swing.GroupLayout(p4);
        p4.setLayout(p4Layout);
        p4Layout.setHorizontalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p4Layout.createSequentialGroup()
                        .addComponent(search4, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(timKiem4))
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(319, 319, 319))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p4Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 929, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        p4Layout.setVerticalGroup(
            p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel26)
                .addGap(18, 18, 18)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(search4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(timKiem4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        parentPanel.add(p4, "card5");

        p5.setBackground(new java.awt.Color(255, 255, 255));

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel25.setText("Nhập mã sinh viên:");
        jLabel25.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        seeMark.setText("Xem điểm");
        seeMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeMarkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p5Layout = new javax.swing.GroupLayout(p5);
        p5.setLayout(p5Layout);
        p5Layout.setHorizontalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5Layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(search5, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(seeMark)
                .addContainerGap(507, Short.MAX_VALUE))
        );
        p5Layout.setVerticalGroup(
            p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p5Layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(p5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(search5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seeMark))
                .addContainerGap(455, Short.MAX_VALUE))
        );

        parentPanel.add(p5, "card6");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(parentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(parentPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void diemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_diemMousePressed
        // TODO add your handling code here:
        resetColorAll();
        setColor(diem);
        choosePanel(p5);
    }//GEN-LAST:event_diemMousePressed

    private void trangChuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trangChuMousePressed
        // TODO add your handling code here:
        resetColorAll();
        setColor(trangChu);
         choosePanel(p1);
        
    }//GEN-LAST:event_trangChuMousePressed

    private void sinhVienMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sinhVienMousePressed
        // TODO add your handling code here:]
        resetColorAll();
        setColor(sinhVien);
         choosePanel(p2);
    }//GEN-LAST:event_sinhVienMousePressed

    private void monHocMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_monHocMousePressed
        // TODO add your handling code here:
        resetColorAll();
        setColor(monHoc);
         choosePanel(p3);
    }//GEN-LAST:event_monHocMousePressed

    private void bangDiemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bangDiemMousePressed
        // TODO add your handling code here:
        resetColorAll();
        setColor(bangDiem);
         choosePanel(p4);
    }//GEN-LAST:event_bangDiemMousePressed

    //Mon hoc
    private void refresh3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh3ActionPerformed
        // TODO add your handling code here:
        maMon3.setText("");
        tenMon3.setText("");
        soTin3.setText("");
        loadSubject();
    }//GEN-LAST:event_refresh3ActionPerformed
    private void add3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add3ActionPerformed
        // TODO add your handling code here:
       
        int st=Integer.parseInt(soTin3.getText());
        if(st<0||st>10){
            JOptionPane.showMessageDialog(this,"Số tín phải nằm trong khoảng từ 0-10");
        }else{
            Subject s=new Subject();
            s.setMaMon(Integer.parseInt(maMon3.getText()));
            s.setTenMon(tenMon3.getText());
            s.setSoTin(st);
            subjectDao.addSubject(s);
            loadSubject();
        }
        
    }//GEN-LAST:event_add3ActionPerformed
    private void edit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit3ActionPerformed
        // TODO add your handling code here:
        int row=subjectTable.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(this,"Vui lòng chọn 1 dòng");
        }
        else{
            int id=(int) subjectTable.getValueAt(row,0);
            Subject s=new Subject();
            s=subjectDao.getSubjectById(id);
            maMon3.setText(String.valueOf(s.getMaMon()));
            tenMon3.setText(s.getTenMon());
            soTin3.setText(String.valueOf(s.getSoTin()));
        
        }
    }//GEN-LAST:event_edit3ActionPerformed
    private void delete3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete3ActionPerformed
        // TODO add your handling code here:
        int row=subjectTable.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(this,"Vui lòng chọn 1 dòng");
        }else{
            int confirm=JOptionPane.showConfirmDialog(this,"Bạn chắc chắn muốn xóa");
            if(confirm==JOptionPane.YES_OPTION){
                int id=(int) subjectTable.getValueAt(row,0);
                subjectDao.deleteSubject(id);
                loadSubject();
            }
        }
    }//GEN-LAST:event_delete3ActionPerformed
    private void submit3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit3ActionPerformed
        // TODO add your handling code here:
        int st=Integer.parseInt(soTin3.getText());
        if(st<0||st>10){
            JOptionPane.showMessageDialog(this,"Số tín phải nằm trong khoảng từ 0-10");
        }else{
            Subject s=new Subject();
            s.setMaMon(Integer.parseInt(maMon3.getText()));
            s.setTenMon(tenMon3.getText());
            s.setSoTin(st);
            subjectDao.updateSubject(s);
            loadSubject();
        }
    }//GEN-LAST:event_submit3ActionPerformed
    private void timKiem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiem3ActionPerformed
        // TODO add your handling code here:
        String name=search3.getText();
        List<Subject> subjects=null;
        if(name.trim().length()==0){
           subjects=subjectDao.getALLSubject();
        } else{
            try {
                subjects=subjectDao.findAllSubjectByName(name);
            } catch (SQLException ex) {
                Logger.getLogger(GiaoDien1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        dTM3.setRowCount(0);
        setTableData3(subjects);
    }//GEN-LAST:event_timKiem3ActionPerformed

    private void delete2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete2ActionPerformed
        // TODO add your handling code here:
        int row=studentTable.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(this,"Vui lòng chọn 1 dòng");
        } else{
            int confirm=JOptionPane.showConfirmDialog(this,"Bạn chắc chắn muốn xóa");
            if(confirm==JOptionPane.YES_OPTION){
                int id=(int) studentTable.getValueAt(row,0);
                studentDao.deleteStudent(id);
                loadStudent();
            }
        }
    }//GEN-LAST:event_delete2ActionPerformed

    private void add2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add2ActionPerformed
        // TODO add your handling code here:
        new AddStudent(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_add2ActionPerformed

    private void edit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit2ActionPerformed
        // TODO add your handling code here:
        int row=studentTable.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(this,"Vui lòng chọn 1 dòng");
        } else{
             int id=(int) studentTable.getValueAt(row,0);
             new EditStudent(id,this,rootPaneCheckingEnabled).setVisible(true);
        }  
    }//GEN-LAST:event_edit2ActionPerformed

    private void timKiem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiem2ActionPerformed
        // TODO add your handling code here:
        String name=search2.getText();
       List<Student> students=null;
        if(name.trim().length()==0){
            students=studentDao.getAllStudent();
        }else{
            try {
                students=studentDao.findAllStudentByName(name);
            } catch (SQLException ex) {
                Logger.getLogger(GiaoDien1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        dTM2.setRowCount(0);
        setTableData2(students);
    }//GEN-LAST:event_timKiem2ActionPerformed

    private void refresh4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refresh4ActionPerformed
        // TODO add your handling code here:
        maBangDiem4.setText("");
        maMon4.setText("");
        lopMon4.setText("");
        ngayThi4.setText("");
        loadMarkTable();
    }//GEN-LAST:event_refresh4ActionPerformed

    private void delete4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delete4ActionPerformed
        // TODO add your handling code here:
        int row=mTTable.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(this,"Vui lòng chọn 1 dòng");     
        }else{
            int confirm=JOptionPane.showConfirmDialog(this,"Bạn có chắc chắn muốn xóa");
            if(confirm==JOptionPane.YES_OPTION){
                int id=(int) mTTable.getValueAt(row,0);
                markTableDao.deleteMarkTable(id);
            }
        }
    }//GEN-LAST:event_delete4ActionPerformed

    private void add4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add4ActionPerformed
        // TODO add your handling code here:
        MarkTable markTable=new MarkTable();
        markTable.setMaBangDiem(Integer.parseInt(maBangDiem4.getText()));
        markTable.setMaMon(Integer.parseInt(maMon4.getText()));
        markTable.setLopMon(lopMon4.getText());
        markTable.setNgayThi(Date.valueOf(ngayThi4.getText()));
        markTable.setHocKi((String) hocKy4.getSelectedItem());
        markTableDao.addMarkTable(markTable);
        loadMarkTable();
    }//GEN-LAST:event_add4ActionPerformed

    private void edit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit4ActionPerformed
        // TODO add your handling code here:
        int row=mTTable.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(this,"Vui lòng chọn 1 dòng");
        }else{
            int id=(int) mTTable.getValueAt(row,0);
            MarkTable markTable=markTableDao.getMarkTableById(id);
            maBangDiem4.setText(String.valueOf(markTable.getMaBangDiem()));
            maMon4.setText(String.valueOf(markTable.getMaMon()));
            lopMon4.setText(markTable.getLopMon());
            ngayThi4.setText(String.valueOf(markTable.getNgayThi()));
            hocKy4.setSelectedItem(markTable.getHocKi());
        }
    }//GEN-LAST:event_edit4ActionPerformed

    private void submit4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submit4ActionPerformed
        // TODO add your handling code here:
         MarkTable markTable=new MarkTable();
        markTable.setMaBangDiem(Integer.parseInt(maBangDiem4.getText()));
        markTable.setMaMon(Integer.parseInt(maMon4.getText()));
        markTable.setLopMon(lopMon4.getText());
        markTable.setNgayThi(Date.valueOf(ngayThi4.getText()));
        markTable.setHocKi((String) hocKy4.getSelectedItem());
        markTableDao.updateMarkTable(markTable);
        loadMarkTable();
        
    }//GEN-LAST:event_submit4ActionPerformed

    private void timKiem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_timKiem4ActionPerformed
        // TODO add your handling code here:
        String name=search4.getText();
        List<MarkTable> markTables=null;
        if(name.trim().length()==0){
            markTables=markTableDao.getAllMarkTable();
        } else{
            try {
                markTables=markTableDao.findMarkTableByName(name);
            } catch (SQLException ex) {
                Logger.getLogger(GiaoDien1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        dTM4.setRowCount(0);
        setTableData4(markTables);
    }//GEN-LAST:event_timKiem4ActionPerformed

    private void seeMark4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeMark4ActionPerformed
        // TODO add your handling code here:
        int row=mTTable.getSelectedRow();
        if(row==-1){
            JOptionPane.showMessageDialog(this,"Vui long chon 1 dong");
        }
        else{
            int maBangDiem=(int) mTTable.getValueAt(row,0);
            new ListMark(maBangDiem).setVisible(true);
        }
    }//GEN-LAST:event_seeMark4ActionPerformed

    private void seeMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeMarkActionPerformed
        // TODO add your handling code here:
        int id=Integer.parseInt(search5.getText());
        new MarkOfStudent(id).setVisible(true);
    }//GEN-LAST:event_seeMarkActionPerformed
    //Sinh vien
    
    public void setColor(JPanel panel){
        panel.setBackground(new java.awt.Color(27,0,35));  
    }
    public void resetColor(JPanel panel){
        panel.setBackground(new java.awt.Color(54,39,89));  
    }
    public void resetColorAll(){
        resetColor(trangChu);
        resetColor(sinhVien);
        resetColor(monHoc);
        resetColor(bangDiem);
        resetColor(diem);
    }
    public void choosePanel(JPanel panel){
        parentPanel.removeAll();
        parentPanel.add(panel);
        parentPanel.repaint();
        parentPanel.revalidate();
    }
    public void loadSubject(){
        dTM3.setRowCount(0);
        setTableData3(subjectDao.getALLSubject());
    }
    public void loadStudent(){
        dTM2.setRowCount(0);
        setTableData2(studentDao.getAllStudent());
    }
    public void loadMarkTable(){
        dTM4.setRowCount(0);
        setTableData4(markTableDao.getAllMarkTable());
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GiaoDien1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GiaoDien1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GiaoDien1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GiaoDien1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GiaoDien1().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add2;
    private javax.swing.JButton add3;
    private javax.swing.JButton add4;
    private javax.swing.JPanel bangDiem;
    private javax.swing.JButton delete2;
    private javax.swing.JButton delete3;
    private javax.swing.JButton delete4;
    private javax.swing.JPanel diem;
    private javax.swing.JButton edit2;
    private javax.swing.JButton edit3;
    private javax.swing.JButton edit4;
    private javax.swing.JComboBox<String> hocKy4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField lopMon4;
    private javax.swing.JTable mTTable;
    private javax.swing.JTextField maBangDiem4;
    private javax.swing.JTextField maMon3;
    private javax.swing.JTextField maMon4;
    private javax.swing.JPanel monHoc;
    private javax.swing.JTextField ngayThi4;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel p4;
    private javax.swing.JPanel p5;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JButton refresh3;
    private javax.swing.JButton refresh4;
    private javax.swing.JTextField search2;
    private javax.swing.JTextField search3;
    private javax.swing.JTextField search4;
    private javax.swing.JTextField search5;
    private javax.swing.JButton seeMark;
    private javax.swing.JButton seeMark4;
    private javax.swing.JPanel sinhVien;
    private javax.swing.JTextField soTin3;
    private javax.swing.JTable studentTable;
    private javax.swing.JTable subjectTable;
    private javax.swing.JButton submit3;
    private javax.swing.JButton submit4;
    private javax.swing.JTextField tenMon3;
    private javax.swing.JButton timKiem2;
    private javax.swing.JButton timKiem3;
    private javax.swing.JButton timKiem4;
    private javax.swing.JPanel trangChu;
    // End of variables declaration//GEN-END:variables
}
